// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz2wnIhMQPcPfWSAR0grjZF0uzo1TTw6E',
    appId: '1:98138805062:android:14391b97197d2c98e3cb47',
    messagingSenderId: '98138805062',
    projectId: 'vibration-f5137',
    storageBucket: 'vibration-f5137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXwwl2Fe7qH6DFYsB9W5rMAtcmwKaXWTY',
    appId: '1:98138805062:ios:8c0947955028f7cce3cb47',
    messagingSenderId: '98138805062',
    projectId: 'vibration-f5137',
    storageBucket: 'vibration-f5137.appspot.com',
    iosClientId: '98138805062-duhn19hsqmuqiies5p8vpmcjbeq12bkn.apps.googleusercontent.com',
    iosBundleId: 'com.thomson.vibration',
  );
}
